# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'easytrans' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  	pod 'JPush'
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'

  # Pods for easytrans

end
